# Generated by Django 4.2.5 on 2023-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_result_correct_anwers_result_skipped_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
