# Generated by Django 4.2.5 on 2023-09-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_quesmodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subject',
            field=models.CharField(blank=True, choices=[('Maths', 'Maths'), ('Science', 'Science')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Science', 'Science')], max_length=200),
        ),
    ]
