# Generated by Django 4.2.5 on 2023-09-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0007_result_subject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModel',
            new_name='ExamModel',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='ans',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='op1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='op2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='op3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='op4',
            new_name='option4',
        ),
        migrations.RenameField(
            model_name='exammodel',
            old_name='question',
            new_name='question_name',
        ),
    ]
